<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../common.props"/>
    <Import Project="../../configureawait.props"/>

    <ItemGroup>
        <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.14.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fake.ObjectStorage\Fake.ObjectStorage.csproj"/>
    </ItemGroup>

</Project>
