// <auto-generated />
using System;
using Fake.EntityFrameworkCore;
using Fake.FileManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fake.FileManagement.Infrastructure.Migrations;

[DbContext(typeof(FileManagementDbContext))]
[Migration("20260320010000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("_Fake_DatabaseProvider", DatabaseProvider.MySql)
            .HasAnnotation("ProductVersion", "8.0.13")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Fake.FileManagement.Domain.FileAggregate.StoredFile", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("char(36)")
                    .HasColumnName("ConcurrencyStamp");

                b.Property<string>("ContentType")
                    .HasMaxLength(128)
                    .HasColumnType("varchar(128)");

                b.Property<DateTime>("CreateTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("CreateTime");

                b.Property<Guid>("CreateUserId")
                    .HasColumnType("char(36)")
                    .HasColumnName("CreateUserId");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)");

                b.Property<bool>("IsDeleted")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false)
                    .HasColumnName("IsDeleted");

                b.Property<long>("Size")
                    .HasColumnType("bigint");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("StorageSource")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.Property<DateTime>("UpdateTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("UpdateTime");

                b.Property<Guid>("UpdateUserId")
                    .HasColumnType("char(36)")
                    .HasColumnName("UpdateUserId");

                b.HasKey("Id");

                b.HasIndex("Status");

                b.HasIndex("StorageSource");

                b.ToTable("stored_file", (string)null);
            });
#pragma warning restore 612, 618
    }
}
