<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../../common.module.props"/>
    <Import Project="../../../configureawait.props"/>

    <PropertyGroup>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Fake.AspNetCore\Fake.AspNetCore.csproj"/>
        <ProjectReference Include="..\..\..\src\Fake.Ddd.Application\Fake.Ddd.Application.csproj"/>
        <ProjectReference Include="..\..\..\src\Fake.ObjectMapping.AutoMapper\Fake.ObjectMapping.AutoMapper.csproj"/>
        <ProjectReference Include="..\..\..\src\Fake.ObjectStorage\Fake.ObjectStorage.csproj"/>
        <ProjectReference Include="..\Fake.FileManagement.Domain\Fake.FileManagement.Domain.csproj"/>
    </ItemGroup>

</Project>
