<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../common.props" />
    <Import Project="../../configureawait.props" />

    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.3.1" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
        <PackageReference Include="Autofac.Extras.DynamicProxy" Version="8.0.1" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Fake.Castle\Fake.Castle.csproj" />
        <ProjectReference Include="..\Fake.Core\Fake.Core.csproj" />
    </ItemGroup>

</Project>
