<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../common.props"/>
    <Import Project="../../configureawait.props"/>

    <ItemGroup>
        <PackageReference Include="FreeRedis" Version="1.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fake.Caching\Fake.Caching.csproj"/>
    </ItemGroup>

</Project>
