<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.test.props"/>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Fake.EventBus.RabbitMQ\Fake.EventBus.RabbitMQ.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
